/**
 * Regression coverage for the behaviors changed in the "Address CodeRabbit
 * review" pass. Each block ties back to a specific review finding so a
 * future refactor that accidentally reverts one is caught in CI.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { defaultStoreDir } from '../../src/core/store/paths.js';
import {
  resolveScopeId,
  resolveScopeOrDefault,
} from '../../src/core/store/scopeHelpers.js';
import { openDb } from '../../src/core/store/db.js';
import { ValidationError } from '../../src/core/errors.js';
import { toEpochMs } from '../../src/core/importers/importer.js';
import { looksLikeToken, generateToken } from '../../src/core/tools/tokens.js';
import { StubEmbeddingProvider } from '../../src/core/embeddings/stub.js';
import { loadConfig } from '../../src/core/config.js';
import { makeFixture, type Fixture } from '../helpers/factory.js';

describe('review fixes', () => {
  describe('paths.defaultStoreDir — empty env var treated as unset', () => {
    let saved: string | undefined;
    beforeEach(() => {
      saved = process.env.DARKCONTEXT_HOME;
    });
    afterEach(() => {
      if (saved === undefined) delete process.env.DARKCONTEXT_HOME;
      else process.env.DARKCONTEXT_HOME = saved;
    });

    it('empty string falls back to the homedir default (not a relative path)', () => {
      process.env.DARKCONTEXT_HOME = '';
      expect(defaultStoreDir()).toMatch(/\/\.darkcontext$/);
    });

    it('whitespace-only is treated the same as empty', () => {
      process.env.DARKCONTEXT_HOME = '   ';
      expect(defaultStoreDir()).toMatch(/\/\.darkcontext$/);
    });
  });

  describe('scopeHelpers — empty scope names rejected, inserts atomic', () => {
    let dir: string;
    beforeEach(() => { dir = mkdtempSync(join(tmpdir(), 'dcx-sh-')); });
    afterEach(() => rmSync(dir, { recursive: true, force: true }));

    it('empty string throws ValidationError instead of silently routing to default', () => {
      const db = openDb({ path: join(dir, 'store.db') });
      try {
        expect(() => resolveScopeOrDefault(db.raw, '')).toThrow(ValidationError);
        expect(() => resolveScopeOrDefault(db.raw, '   ')).toThrow(ValidationError);
      } finally {
        db.close();
      }
    });

    it('undefined still resolves to the default scope', () => {
      const db = openDb({ path: join(dir, 'store.db') });
      try {
        const id = resolveScopeOrDefault(db.raw, undefined);
        expect(id).toBeGreaterThan(0);
      } finally {
        db.close();
      }
    });

    it('resolveScopeId is idempotent under repeat calls (ON CONFLICT DO NOTHING)', () => {
      const db = openDb({ path: join(dir, 'store.db') });
      try {
        const first = resolveScopeId(db.raw, 'race');
        const second = resolveScopeId(db.raw, 'race');
        expect(first).toBe(second);
      } finally {
        db.close();
      }
    });
  });

  describe('importer.toEpochMs — digit-only strings', () => {
    it('parses epoch-seconds string and converts to ms', () => {
      expect(toEpochMs('1700000000')).toBe(1_700_000_000_000);
    });
    it('parses epoch-ms string directly', () => {
      expect(toEpochMs('1700000000000')).toBe(1_700_000_000_000);
    });
    it('parses fractional epoch-seconds', () => {
      expect(toEpochMs('1700000000.5')).toBe(1_700_000_000_500);
    });
    it('still parses ISO strings', () => {
      expect(toEpochMs('2024-01-01T00:00:00Z')).toBe(Date.parse('2024-01-01T00:00:00Z'));
    });
  });

  describe('tokens.looksLikeToken — strict shape', () => {
    it('accepts tokens generated by generateToken', () => {
      for (let i = 0; i < 5; i++) expect(looksLikeToken(generateToken())).toBe(true);
    });
    it('rejects tokens that are too short, too long, or use wrong chars', () => {
      expect(looksLikeToken('dcx_tooshort')).toBe(false);
      expect(looksLikeToken('dcx_' + 'a'.repeat(42))).toBe(false); // 42, need 43
      expect(looksLikeToken('dcx_' + 'a'.repeat(44))).toBe(false);
      expect(looksLikeToken('dcx_' + '!'.repeat(43))).toBe(false);
    });
    it('rejects values without the prefix', () => {
      expect(looksLikeToken('wrong_' + 'a'.repeat(43))).toBe(false);
    });
  });

  describe('StubEmbeddingProvider — dimension validation', () => {
    it('rejects non-positive integer dimensions at construction', () => {
      expect(() => new StubEmbeddingProvider(0)).toThrow(RangeError);
      expect(() => new StubEmbeddingProvider(-1)).toThrow(RangeError);
      expect(() => new StubEmbeddingProvider(1.5)).toThrow(RangeError);
      expect(() => new StubEmbeddingProvider(Number.NaN)).toThrow(RangeError);
    });
    it('accepts any positive integer', () => {
      expect(() => new StubEmbeddingProvider(1)).not.toThrow();
      expect(() => new StubEmbeddingProvider(4096)).not.toThrow();
    });
  });

  describe('loadConfig — DARKCONTEXT_DB_PATH env var is honored', () => {
    it('uses env.DARKCONTEXT_DB_PATH when no override is given', () => {
      const c = loadConfig({}, { DARKCONTEXT_DB_PATH: '/var/lib/darkcontext/store.db' });
      expect(c.dbPath).toBe('/var/lib/darkcontext/store.db');
    });
    it('explicit override still wins', () => {
      const c = loadConfig(
        { dbPath: '/explicit.db' },
        { DARKCONTEXT_DB_PATH: '/env.db' }
      );
      expect(c.dbPath).toBe('/explicit.db');
    });
  });

  describe('Scopes.upsert — description updates on second call', () => {
    let fx: Fixture;
    beforeEach(() => { fx = makeFixture(); });
    afterEach(() => fx.cleanup());

    it('an existing scope gets its description updated when a new one is supplied', () => {
      fx.scopes.upsert('research', 'first description');
      const after = fx.scopes.upsert('research', 'second description');
      expect(after.description).toBe('second description');

      // And if we call again WITHOUT a description, nothing should change.
      const unchanged = fx.scopes.upsert('research');
      expect(unchanged.description).toBe('second description');
    });
  });
});
